version: '3.8'
services:
  # Фронтенд - сервер на Node.js Express
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.new
    ports:
      - "${PORT:-80}:80"
    depends_on:
      - backend
    networks:
      - app-network

  # Бэкенд - API сервер на Express
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-3001}:3001"
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://${DB_USER:-user}:${DB_PASSWORD:-password}@db:5432/${DB_NAME:-bitcoin_tracker}
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - app-network

  # Коллектор данных - периодически получает данные из API
  collector:
    build: 
      context: ./collector
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-user}:${DB_PASSWORD:-password}@db:5432/${DB_NAME:-bitcoin_tracker}
      - NODE_ENV=production
    depends_on:
      - db
    restart: always
    networks:
      - app-network

  # База данных PostgreSQL
  db:
    image: postgres:14
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-bitcoin_tracker}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
