version: '3.8'
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - BACKEND_URL=http://backend:3001
      - NODE_ENV=production
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "3001"
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://user:password@db:5432/bitcoin_tracker
      - NODE_ENV=production
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  collector:
    build: 
      context: ./collector
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/bitcoin_tracker
      - NODE_ENV=production
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-bitcoin_tracker}
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
