[build]
builder = "DOCKERFILE"
dockerfilePath = "frontend/Dockerfile"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "frontend"
envVars = [
  { key = "NODE_ENV", value = "production" },
  { key = "NUXT_HOST", value = "0.0.0.0" },
  { key = "NUXT_PORT", value = "3000" }
]

[[services]]
name = "backend"
envVars = [
  { key = "NODE_ENV", value = "production" },
  { key = "DATABASE_URL", value = "${{DATABASE_URL}}" }
]

[[services]]
name = "collector"
envVars = [
  { key = "NODE_ENV", value = "production" },
  { key = "DATABASE_URL", value = "${{DATABASE_URL}}" }
]

[[plugins]]
name = "postgresql" 